/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.bmarques.soap;

import com.bmarques.soap.api.InvoiceWS;

import javax.xml.ws.Endpoint;

public class App {

    public static void main(String[] args) {
        InvoiceWS implementacaoWS = new InvoiceWS();
        String URL = "http://localhost:8080/invoicews";

        System.out.println("InvoiceWS rodando: " + URL);

        //associando URL com implementacao
        Endpoint.publish(URL, implementacaoWS);
    }
}
